In [1]:
# ==========================================
# Lesson 33
# Building the Study Database
# ==========================================

import ee
import geemap

ee.Initialize(project="oc-flux")

Map = geemap.Map()

Map

Map(center=[0, 0], controls=(WidgetControl(options=['position', 'transparent_bg'], position='topright', transp…

In [ ]:
Where Do River Datasets Come From?

Researchers commonly use:

Dataset	Purpose
HydroRIVERS	River centerlines
HydroBASINS	Basin boundaries
HydroSHEDS	DEM-derived drainage
India-WRIS	Indian river information
CWC	Discharge stations

For this course we will mainly use:

HydroRIVERS

because it is globally recognized.

In [ ]:
Understanding HydroRIVERS

HydroRIVERS contains:

River centerlines
River names
Stream order
River length
Connectivity

In [ ]:
Initial Database

Let's create a simple table in Python.

In [6]:
import pandas as pd

rivers = pd.DataFrame({

"River":[

"Ganga",
"Brahmaputra",
"Godavari",
"Krishna",
"Mahanadi",
"Narmada",
"cauvery"

]

})

rivers

         River
0        Ganga
1  Brahmaputra
2     Godavari
3      Krishna
4     Mahanadi
5      Narmada
6      cauvery

In [ ]:
Add Approximate Coordinates

For now we'll use one representative location for each river. Later, we'll replace these with official river reaches.

In [10]:
rivers = pd.DataFrame({

"River":[

"Ganga",
"Brahmaputra",
"Godavari",
"Krishna",
"Mahanadi",
"Narmada",
"cauvery"

],

"Lon":[

83.0120,
91.7440,
81.7830,
80.6480,
85.8500,
75.7000,
79.1400

],

"Lat":[

25.3176,
26.2000,
17.0000,
16.6000,
20.3000,
22.3000,
11.8700

]

})

rivers

         River     Lon      Lat
0        Ganga  83.012  25.3176
1  Brahmaputra  91.744  26.2000
2     Godavari  81.783  17.0000
3      Krishna  80.648  16.6000
4     Mahanadi  85.850  20.3000
5      Narmada  75.700  22.3000
6      cauvery  79.140  11.8700

In [ ]:
Display Rivers on the Map

In [13]:
Map = geemap.Map()

for _, row in rivers.iterrows():

    point = ee.Geometry.Point([
        row["Lon"],
        row["Lat"]
    ])

    Map.addLayer(
        point,
        {"color":"red"},
        row["River"]
    )

Map.centerObject(
    ee.Geometry.Point([82,22]),
    4
)

Map

Map(center=[22, 82], controls=(WidgetControl(options=['position', 'transparent_bg'], position='topright', tran…